### PR TITLE
Inline edit component updates

### PR DESCRIPTION
**Pull request by patsissons**
@jirikavi have a look at these modifications. this would bring your component more inline with how the other generic components operate. Below is a list of the modifications made:

* Minimal style modifications
* view templating
* HTML props
* Enter/Esc key handling
* auto focus & select all on edit
* bootstrap input group
* generic value typing (view model)
* view model commands for each action

### CODE REVIEW

**Comment by patsissons** [comment]
ok @jirikavi I think this one is good to go. Give it a once over and let me know if you have any questions or concerns before we get these updates into `develop`

**Comment by jirikavi** [comment]
Thank you @patsissons  for the review. It looks much more consistent. There are few code constructions or methods I didn't know about and are useful.

one of those can be:

```
  private renderEditor() {
    const { className, props, rest } = this.restProps(x => {
      const { controlId, inputType, keyboard, template, editTemplate } = x;
      return { controlId, inputType, keyboard, template, editTemplate };
    });
```

I was also looking for this:
`Observable.of(this.value())`

Is there any good source for learning about these React features?

```
const control = ReactDOM.findDOMNode(this.refs['control']) as HTMLInputElement;
e: React.KeyboardEvent<any>
```

I am fine with merging it except one thing which I might miss but it doesn't seem to me that it is possible to achieve. I need to pass a command function after saving the new value (mainly due to calling DB update). Is it possible in the current code?

**Comment by patsissons** [comment]
`this.restProps(...)` is a custom function in this framework, a stop-gap until rest/spread is possible in typescript `2.1.3`.

There isn't much good info on doing React stuff, but check out the [TypeScript Handbook](https://github.com/Microsoft/TypeScript-Handbook) and [RxJS API Docs](http://reactivex.io/rxjs/) (though note these are for the newer version so might not be completely compatible).

**Comment by patsissons** [comment]
So the existing strategy for on save callback was to simply attach to the results of the save command (as seen in [the demo](https://github.com/marinels/webrx-react/pull/3/files#diff-12e8c90f614c7a70f5ae86bf69d5ecb2R196). This, however, introduces an issue in that the save operation is a side effect of the save command execution, which means that the result of the save is not a dependency of the command's execution.

My proposal to fix this is to add a new optional param to the constructor to handle the async save operation, in the form `onSave: (value: T) => Observable<T>` (which would default to `x => Observable.of(x)`). This strategy permits both my existing (side effect) saving as well as async dependency saving.

**Comment by jirikavi** [comment]
Ok then I will try to implement your proposal. Thank you for the links Pat.
I will look at them.

po 14. 11. 2016 v 11:29 odesílatel Pat Sissons notifications@github.com
napsal:

**Comment by patsissons** [comment]
@jirikavi i should mention I'm already half done the proposal :)

**Pull request merged**
